---
include:
  - project: 'gitlab-files/yamllint'
    ref: master
    file: 'gitlab-ci.yaml'
  - project: 'gitlab-files/hadolint'
    ref: master
    file: 'gitlab-ci.yaml'
  - project: 'gitlab-files/helm'
    ref: package
    file: 'gitlab-ci.yaml'
  - project: 'gitlab-files/go'
    ref: master
    file: 'gitlab-ci.yaml'
  - project: 'gitlab-files/sonarqube/sonar-scanner'
    ref: master
    file: 'gitlab-ci.yaml'
  - project: 'gitlab-files/docker/dockerize'
    ref: master
    file: 'gitlab-ci.yml'
  - project: 'gitlab-files/gke-helm-deploy'
    ref: impl
    file: 'gitlab-ci.yaml'

stages:
  - lint
  - test
  - sonarqube
  - build
  - docker
  - deploy

yamllint:
  extends: .yamllint
  script:
    - yamllint .gitlab-ci.yml

hadolint:
  extends: .hadolint

helm-lint:
  extends: .helm-lint
  variables:
    HELM_CHART_PATH: "helm"

unit_tests:
  extends: .unit_tests

lint_code:
  extends: .lint_code

race_tests:
  extends: .race_tests

coverage_tests:
  extends: .coverage_tests

sonar-scanner:
  extends: .sonar-scanner
  variables:
    SONAR_PROPERTIES: >
      -Dsonar.sources=.
      -Dsonar.exclusions=**/*_test.go,**/vendor/**
      -Dsonar.tests=.
      -Dsonar.test.inclusions=**/*_test.go
      -Dsonar.test.exclusions=**/vendor/**
      -Dsonar.go.coverage.reportPaths=coverage.out

build:
  extends: .build

docker-build-sha:
  extends: .docker-build-sha

docker-build-release:
  extends: .docker-build-release

gke-helm-deploy:
  extends: .gke-helm-deploy
