---
include:
  - project: 'gitlab-files/hadolint'
    ref: master
    file: 'gitlab-ci.yaml'
  - project: 'gitlab-files/yamllint'
    ref: master
    file: 'gitlab-ci.yaml'
  - project: 'gitlab-files/go'
    ref: master
    file: 'gitlab-ci.yaml'
  - project: 'gitlab-files/docker/docker-build-push'
    ref: fix-before-script
    file: 'gitlab-ci.yml'

stages:
  - lint
  - test
  - build
  - docker-build
  - docker-push

yamllint:
  extends: .yamllint

hadolint:
  extends: .hadolint


unit_tests:
  extends: .unit_tests

lint_code:
  extends: .lint_code

race_tests:
  extends: .race_tests

coverage_tests:
  extends: .coverage_tests

build:
  extends: .build

docker-build:
  extends: .docker-build

docker-push:
  extends: .docker-push
